version: "3.8"

services:
  thread-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: thread-app
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILE_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

volumes:
  logs:

networks:
  app-network:
    driver: bridge
